import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navegation from '@/components/navegation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const navlinks = [
    {
      name: 'home',
      href: '/'
    },
    {
      name: 'dashboard',
      href: '/dashboard'
    },
  ]
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navegation navlinks={navlinks}/>
        {children}
      </body>
    </html>
  )
}
